language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - LARAVEL_VERSION=5.4.*
    - LARAVEL_VERSION=5.5.*
    - LARAVEL_VERSION=5.6.*
    - LARAVEL_VERSION=5.7.*
    - LARAVEL_VERSION=5.8.*

matrix:
  exclude:
  - php: 7.0
    env: LARAVEL_VERSION=5.6.*
  - php: 7.0
    env: LARAVEL_VERSION=5.7.*
  - php: 7.0
    env: LARAVEL_VERSION=5.8.*

before_install:
  - composer self-update --stable -n
  - composer global require --no-progress --no-suggest -n hirak/prestissimo
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update --no-progress --no-suggest -n

install: travis_retry composer install --no-suggest --prefer-dist -n -o

script: vendor/bin/phpunit

branches:
  only:
    - master
